name: dagger
run-name: ${{ github.actor }} is testing with dagger üó°Ô∏è
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dagger Engine
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: latest

      - name: test-docker
        working-directory: ./docker/tests
        run: dagger checks

      - name: test-git-cliff
        working-directory: ./git-cliff/tests
        run: dagger checks

      - name: test-goreleaser
        working-directory: ./goreleaser/tests
        run: dagger checks

      - name: test-markdownlint
        working-directory: ./markdownlint/tests
        run: dagger checks

      - name: test-python
        working-directory: ./python/tests
        run: dagger checks

      - name: test-yamllint
        working-directory: ./yamllint/tests
        run: dagger checks

      - name: test-release
        working-directory: ./release/tests
        run: dagger checks

      - name: test-gocoverage
        working-directory: ./gocoverage/tests
        run: dagger checks

      - name: test-acedt
        working-directory: ./data-tool/tests
        run: dagger checks